#ifndef DOODLE_H
#define DOODLE_H

/* Auto-generated by cbindgen; regenerate with scripts/capi-header.sh --write. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* The C ABI contract version (distinct from the engine version). See doodle_abi_version(). */
#define DOODLE_ABI_VERSION_MAJOR 0
#define DOODLE_ABI_VERSION_MINOR 1


/**
 * The observation-mode granularity (E§8.8): per-statement (default) or per-subexpression.
 */
enum DoodleObservationMode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Per-statement safe points only (the default).
   */
  DoodleObservationMode_Statement = 0,
  /**
   * Adds per-subexpression fine safe points (the "watch your expression evaluate" mode).
   */
  DoodleObservationMode_Subexpression = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleObservationMode DoodleObservationMode;
#else
typedef uint32_t DoodleObservationMode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The result of a fallible C-ABI call: `Ok` on success, else the reason. Fallible calls
 * return this and write their result through an out-parameter (freeze convention 5).
 */
enum DoodleStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The call succeeded; any out-parameters are written.
   */
  DoodleStatus_Ok = 0,
  /**
   * A handle named a freed/reused slot — a use-after-release, forged, or (M7.6) a
   * cross-instance handle (mirrors `ValueError::Stale`).
   */
  DoodleStatus_ErrStaleHandle = 1,
  /**
   * A typed reader was applied to a value of a different kind (e.g. read an int from a
   * string). The value's actual kind is available via `doodle_kind_of`.
   */
  DoodleStatus_ErrWrongKind = 2,
  /**
   * `doodle_as_int` on an integer whose magnitude exceeds `int64_t` (a bignum — read it
   * with `doodle_as_int_decimal`).
   */
  DoodleStatus_ErrIntOutOfRange = 3,
  /**
   * A list/string index was past the end.
   */
  DoodleStatus_ErrIndexOutOfBounds = 4,
  /**
   * `doodle_make_string` was given bytes that are not well-formed UTF-8.
   */
  DoodleStatus_ErrInvalidUtf8 = 5,
  /**
   * `doodle_make_int_decimal` was given text that is not a base-10 integer literal.
   */
  DoodleStatus_ErrMalformedInt = 6,
  /**
   * The config named a Unicode version the engine does not support (S-41).
   */
  DoodleStatus_ErrUnsupportedUnicode = 7,
  /**
   * The program failed to load: a lex/parse/resolve error (its text is copied into
   * `doodle_load`'s `err_buf`).
   */
  DoodleStatus_ErrLoad = 8,
  /**
   * A caller buffer was too small; the required length is written to the `needed`
   * out-parameter and the buffer is left untouched (copy-out, freeze convention 4).
   */
  DoodleStatus_ErrBufferTooSmall = 9,
  /**
   * A required pointer argument was NULL.
   */
  DoodleStatus_ErrNullPointer = 10,
  /**
   * A host-contract violation the engine caught (e.g. resolving a non-suspended instance).
   */
  DoodleStatus_ErrContract = 11,
  /**
   * A Rust panic was caught at the boundary (an engine bug; the firewall of last resort,
   * [`crate::guard`]). The instance should be considered unusable.
   */
  DoodleStatus_ErrPanic = 12,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleStatus DoodleStatus;
#else
typedef uint32_t DoodleStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A driving directive (E§7.3): how far to run before returning to the host.
 */
enum DoodleDirective
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Run to the next capability / raise / fault / completion (a fast run).
   */
  DoodleDirective_RunToCompletion = 0,
  /**
   * Like `RunToCompletion` but also stop at breakpoints and the raise-trap.
   */
  DoodleDirective_Continue = 1,
  /**
   * Stop at the next safe point, in any frame (synonym of `StepInto`).
   */
  DoodleDirective_Step = 2,
  /**
   * Step, descending into calls.
   */
  DoodleDirective_StepInto = 3,
  /**
   * Step, treating a call as one step.
   */
  DoodleDirective_StepOver = 4,
  /**
   * Run until the current frame returns.
   */
  DoodleDirective_StepOut = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleDirective DoodleDirective;
#else
typedef uint32_t DoodleDirective;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which kind of stop a drive reached (E§7.2) — the tag of [`DoodleOutcome`].
 */
enum DoodleOutcomeKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The driven unit finished (`DoodleOutcome::value` is its result, `0` for Void).
   */
  DoodleOutcomeKind_Completed = 0,
  /**
   * A capability must be fulfilled before continuing (`capability`/`request_count`;
   * the arg marshalling is M7.2).
   */
  DoodleOutcomeKind_Suspended = 1,
  /**
   * An `import` reached an unloaded module (`request_count` path segments; the resolver
   * is M7.2).
   */
  DoodleOutcomeKind_SuspendedImport = 2,
  /**
   * Stopped at a safe point (`pause_reason`; `breakpoint_id` when a breakpoint).
   */
  DoodleOutcomeKind_Paused = 3,
  /**
   * An uncaught exception reached the boundary (E§9); `span_*` is its site. Read its
   * described form with `doodle_raised_kind` / `doodle_raised_message`.
   */
  DoodleOutcomeKind_Raised = 4,
  /**
   * A non-resumable engine fault (`fault`).
   */
  DoodleOutcomeKind_Faulted = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleOutcomeKind DoodleOutcomeKind;
#else
typedef uint32_t DoodleOutcomeKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Why a drive paused (E§7.2).
 */
enum DoodlePauseReason
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The active `Step*` directive reached its next safe point.
   */
  DoodlePauseReason_Step = 0,
  /**
   * A breakpoint was hit (`DoodleOutcome::breakpoint_id`).
   */
  DoodlePauseReason_Breakpoint = 1,
  /**
   * A raise was trapped before propagating (E§8.7).
   */
  DoodlePauseReason_RaiseTrap = 2,
  /**
   * The host requested a pause (E§8.8).
   */
  DoodlePauseReason_HostPause = 3,
  /**
   * The drive's bounded-run fuel was spent (S-40) — a resumable slice boundary; re-drive.
   */
  DoodlePauseReason_SliceEnd = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodlePauseReason DoodlePauseReason;
#else
typedef uint32_t DoodlePauseReason;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A non-resumable engine fault (E§7.2/§10). The core's `LimitExceeded(LimitKind)` is
 * flattened into distinct `Limit*` codes (as the wasm surface flattens to string tags).
 */
enum DoodleFault
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The step budget was exhausted (E§10.2).
   */
  DoodleFault_LimitStepBudget = 0,
  /**
   * The heap-byte ceiling was exceeded (E§10.2).
   */
  DoodleFault_LimitHeap = 1,
  /**
   * The non-tail stack-depth limit was exceeded (E§10.2).
   */
  DoodleFault_LimitStackDepth = 2,
  /**
   * The tail-history bound was exceeded (E§8.3).
   */
  DoodleFault_LimitTailHistory = 3,
  /**
   * A single op's result would exceed the per-op result cap (the latency rail, E§10.2).
   */
  DoodleFault_LimitOpResult = 4,
  /**
   * The host cancelled the drive (E§10.1).
   */
  DoodleFault_Cancelled = 5,
  /**
   * A suspending capability was reached inside a foreign/native callback (E§5.4, S-15).
   */
  DoodleFault_NestedSuspend = 6,
  /**
   * An internal invariant was violated (an engine bug).
   */
  DoodleFault_Internal = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleFault DoodleFault;
#else
typedef uint32_t DoodleFault;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * An engine-provided built-in intrinsic a host can register by identity (E§5.5), without
 * supplying a callback. The synchronous ones (`Print`/`Length`/…) run inline; the
 * capabilities (`ReadLine`/`DrawLine`/`SetTurtle`/`ClearCanvas`) suspend to the host.
 */
enum DoodleBuiltin
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * `print(value)` — renders a value and a newline to the output sink (synchronous).
   */
  DoodleBuiltin_Print = 0,
  /**
   * `length(x)` — the length of a string/list/dict/bytes (synchronous).
   */
  DoodleBuiltin_Length = 1,
  /**
   * `each(list) do (x) … end` — a native block-consumer (synchronous, reentrant).
   */
  DoodleBuiltin_Each = 2,
  /**
   * `encode(string) -> bytes` — UTF-8 encode (synchronous).
   */
  DoodleBuiltin_Encode = 3,
  /**
   * `decode(bytes) -> string` — UTF-8 decode (synchronous).
   */
  DoodleBuiltin_Decode = 4,
  /**
   * `read_line() -> string` — a suspending input capability.
   */
  DoodleBuiltin_ReadLine = 5,
  /**
   * `sin(x) -> float` (synchronous, deterministic libm).
   */
  DoodleBuiltin_Sin = 6,
  /**
   * `cos(x) -> float` (synchronous, deterministic libm).
   */
  DoodleBuiltin_Cos = 7,
  /**
   * `draw_line(x0,y0,x1,y1,r,g,b,a)` — a suspending turtle capability.
   */
  DoodleBuiltin_DrawLine = 8,
  /**
   * `set_turtle(x,y,heading,visible)` — a suspending turtle capability.
   */
  DoodleBuiltin_SetTurtle = 9,
  /**
   * `clear_canvas()` — a suspending turtle capability.
   */
  DoodleBuiltin_ClearCanvas = 10,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleBuiltin DoodleBuiltin;
#else
typedef uint32_t DoodleBuiltin;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A value's kind (E§4.4), the C mirror of `doodle_core`'s `Kind`.
 */
enum DoodleKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * `nil` (L§4.9).
   */
  DoodleKind_Nil = 0,
  /**
   * A boolean (L§4.1).
   */
  DoodleKind_Bool = 1,
  /**
   * An integer of any magnitude (L§4.2).
   */
  DoodleKind_Int = 2,
  /**
   * A float (L§4.3).
   */
  DoodleKind_Float = 3,
  /**
   * A string (L§4.4).
   */
  DoodleKind_String = 4,
  /**
   * A byte string (L§4.5).
   */
  DoodleKind_Bytes = 5,
  /**
   * A list (L§4.6).
   */
  DoodleKind_List = 6,
  /**
   * A dict (L§4.7).
   */
  DoodleKind_Dict = 7,
  /**
   * A record (L§4.14).
   */
  DoodleKind_Record = 8,
  /**
   * A callable (L§6).
   */
  DoodleKind_Callable = 9,
  /**
   * A module value (L§9).
   */
  DoodleKind_Module = 10,
  /**
   * A type value (L§4.12).
   */
  DoodleKind_Type = 11,
  /**
   * A foreign (host) value (E§4.5).
   */
  DoodleKind_Foreign = 12,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleKind DoodleKind;
#else
typedef uint32_t DoodleKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * An opaque instance configuration under construction. Built with `doodle_config_new`,
 * mutated with the `doodle_config_set_*` setters, consumed by `doodle_load`, and released
 * with `doodle_config_free`.
 */
typedef struct DoodleConfig DoodleConfig;

/**
 * A loaded Doodle program: the engine [`Instance`] plus a little host-facing state — the
 * described form of its most recent uncaught raise (for `doodle_raised_kind`/`_message`) and
 * the bound argument handles of a parked capability request (for `doodle_capability_arg`).
 * Opaque to C.
 */
typedef struct DoodleInstance DoodleInstance;

/**
 * A host-extension registry under construction (E§5.5). Built with `doodle_registry_new`,
 * populated in order with `doodle_registry_add_builtin`, then **consumed** by
 * `doodle_load_with_registry`. Opaque to C.
 */
typedef struct DoodleRegistry DoodleRegistry;

typedef struct Option_DoodleFinalizer Option_DoodleFinalizer;

/**
 * An opaque, per-instance value handle (E§4.2), crossing the ABI as a plain `uint64_t`.
 * Round-trips the engine's internal `Handle` bits; the host treats it as opaque and must
 * [`doodle_release`](crate::value::doodle_release) handles it no longer needs. `0` is the
 * reserved null handle (no value), never a live handle.
 */
typedef uint64_t DoodleHandle;

/**
 * The result of a drive (E§7.2), written by `doodle_drive`/`doodle_resolve`. A flat
 * `#[repr(C)]` struct (not a union — a union in a frozen header cannot grow safely): each
 * field is meaningful only for the `kind`s named in its doc, others are `0`/false. The
 * `reserved` tail is growth room — a future field claims a reserved slot without changing
 * the struct's size or layout (freeze convention 2).
 */
typedef struct DoodleOutcome {
  /**
   * Which stop was reached (the tag).
   */
  DoodleOutcomeKind kind;
  /**
   * `Paused`: why.
   */
  DoodlePauseReason pause_reason;
  /**
   * `Faulted`: which fault.
   */
  DoodleFault fault;
  /**
   * `Paused` + `pause_reason == Breakpoint`: the breakpoint id.
   */
  uint32_t breakpoint_id;
  /**
   * `Suspended`: the capability id. `SuspendedImport`: the importing module id.
   */
  uint32_t capability;
  /**
   * `Suspended`: the number of bound argument handles. `SuspendedImport`: the number of
   * dotted path segments. (The M7.2 accessors read the elements.)
   */
  uint32_t request_count;
  /**
   * `Raised`: whether `span_start`/`span_end` name the raising site.
   */
  bool has_span;
  /**
   * `Raised`: the raising site's start byte offset (when `has_span`).
   */
  uint32_t span_start;
  /**
   * `Raised`: the raising site's end byte offset (when `has_span`).
   */
  uint32_t span_end;
  /**
   * `Completed`: the result value (`0` for Void; a reentrant `fn` return populates it once
   * the boundary can intern one, M7.3). A **host-owned** handle when non-zero —
   * `doodle_release` it. `0` for every other kind (a raised value is read in described form
   * via `doodle_raised_kind`/`_message`).
   */
  DoodleHandle value;
  /**
   * Reserved for additive growth (freeze convention 2); always written as `0`.
   */
  uint64_t reserved[4];
} DoodleOutcome;

/**
 * The null handle: the absence of a value (a `to`/module result, an empty outcome slot).
 */
#define DOODLE_NULL_HANDLE 0

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the Doodle engine version as a NUL-terminated C string.
 *
 * The returned pointer is valid for the lifetime of the program and must not
 * be freed by the caller.
 */
const char *doodle_version(void);

/**
 * Returns the C ABI contract version as `(major << 16) | minor` — distinct from the
 * engine version ([`doodle_version`]). A host compiled against `doodle.h` compares this
 * against the header's `DOODLE_ABI_VERSION_MAJOR`/`_MINOR` at load: a differing **major**
 * is incompatible; a newer **minor** is backward-compatible (additive only).
 */
uint32_t doodle_abi_version(void);

/**
 * Creates a config with the engine defaults (E§3.1): default limits, statement-granularity
 * observation, and the engine's pinned Unicode version. Returns NULL only on allocation
 * failure. Free it with `doodle_config_free` (loading does not consume it).
 */
struct DoodleConfig *doodle_config_new(void);

/**
 * Frees a config created by `doodle_config_new`. NULL is a no-op. The config is the host's
 * to free whether or not it was passed to `doodle_load` (load copies what it needs).
 *
 * # Safety
 * `config` must be a pointer returned by `doodle_config_new` and not already freed.
 */
void doodle_config_free(struct DoodleConfig *config);

/**
 * Sets the resource limits (E§10.2): the step budget, heap-byte ceiling, non-tail stack
 * depth, and the per-operation result-size cap (the latency rail — `UINT64_MAX` disables
 * it). No-op on a NULL config.
 *
 * # Safety
 * `config` must be a live pointer from `doodle_config_new` (or NULL).
 */
void doodle_config_set_limits(struct DoodleConfig *config,
                              uint64_t step_budget,
                              uint64_t heap_bytes,
                              uint32_t stack_depth,
                              uint64_t max_op_result_bytes);

/**
 * Sets the observation-mode granularity (E§8.8). No-op on a NULL config.
 *
 * # Safety
 * `config` must be a live pointer from `doodle_config_new` (or NULL).
 */
void doodle_config_set_observation_mode(struct DoodleConfig *config, DoodleObservationMode mode);

/**
 * Sets the **target Unicode version** the host expects (S-41, the replay guard): a
 * recording made under one UCD version fails to load under another rather than diverging
 * silently on grapheme/normalization behavior (E§11). A `major` of `0` clears it (use the
 * engine's pinned version). No-op on a NULL config.
 *
 * # Safety
 * `config` must be a live pointer from `doodle_config_new` (or NULL).
 */
void doodle_config_set_target_unicode(struct DoodleConfig *config,
                                      uint16_t major,
                                      uint16_t minor,
                                      uint16_t micro);

/**
 * Drives `instance` under `directive` to its next stop, writing the result to `out_outcome`
 * (E§7.3). Unbounded (runs until a capability / pause / raise / fault / completion); use
 * [`doodle_drive_slice`] to bound the run with fuel.
 *
 * # Safety
 * `instance` must be a live pointer from [`doodle_load`]; `out_outcome` must be writable.
 */
DoodleStatus doodle_drive(struct DoodleInstance *instance,
                          DoodleDirective directive,
                          struct DoodleOutcome *out_outcome);

/**
 * Like [`doodle_drive`] but runs at most `fuel` statement safe points before yielding a
 * resumable `Paused(SliceEnd)` (S-40) — the host's cooperative-yield point. Re-drive to
 * continue.
 *
 * # Safety
 * As [`doodle_drive`].
 */
DoodleStatus doodle_drive_slice(struct DoodleInstance *instance,
                                DoodleDirective directive,
                                uint64_t fuel,
                                struct DoodleOutcome *out_outcome);

/**
 * Requests cancellation (E§10.1): the drive tears down to `Faulted(Cancelled)` at its next
 * safe point. Idempotent; callable from another thread while a drive runs (the cancel flag
 * is atomic). No-op on NULL.
 *
 * # Safety
 * `instance` must be a live pointer from [`doodle_load`] (or NULL).
 */
void doodle_cancel(const struct DoodleInstance *instance);

/**
 * Writes the `index`-th bound argument handle of the parked capability request (E§7.5) to
 * `out_handle`. The handle is **host-owned** (S-17): read its value (`doodle_as_*` etc.) and
 * `doodle_release` it. `ErrContract` if the instance is not suspended on a capability;
 * `ErrIndexOutOfBounds` if `index >= DoodleOutcome::request_count`.
 *
 * # Safety
 * `instance` must be a live pointer from [`doodle_load`]; `out_handle` must be writable.
 */
DoodleStatus doodle_capability_arg(const struct DoodleInstance *instance,
                                   uint32_t index,
                                   DoodleHandle *out_handle);

/**
 * Resolves a parked capability suspension (E§7.5) with `value` as its result, then drives on
 * and writes the next stop to `out_outcome`. `value` becomes the capability call's result (a
 * `to` capability ignores it, yielding Void). `ErrContract` if the instance is not suspended
 * on a capability.
 *
 * # Safety
 * `instance` must be a live pointer from [`doodle_load`]; `out_outcome` must be writable.
 */
DoodleStatus doodle_resolve(struct DoodleInstance *instance,
                            DoodleHandle value,
                            struct DoodleOutcome *out_outcome);

/**
 * Resolves a parked capability suspension (E§7.5) by **raising** `value` at the capability
 * call site (E§9), then drives on. `ErrContract` if not suspended on a capability.
 *
 * # Safety
 * As [`doodle_resolve`].
 */
DoodleStatus doodle_resolve_raise(struct DoodleInstance *instance,
                                  DoodleHandle value,
                                  struct DoodleOutcome *out_outcome);

/**
 * Copies the described **kind** slug of the instance's most recent `Raised` outcome (E§9)
 * into `buf` (copy-out; `out_len` gets the full length). `DoodleStatus_ErrContract` if the
 * last drive did not raise.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_raised_kind(const struct DoodleInstance *instance,
                                uint8_t *buf,
                                uintptr_t cap,
                                uintptr_t *out_len);

/**
 * Copies the **message** of the instance's most recent `Raised` outcome (E§9) into `buf`
 * (copy-out). `DoodleStatus_ErrContract` if the last drive did not raise.
 *
 * # Safety
 * As [`doodle_raised_kind`].
 */
DoodleStatus doodle_raised_message(const struct DoodleInstance *instance,
                                   uint8_t *buf,
                                   uintptr_t cap,
                                   uintptr_t *out_len);

/**
 * Copies the instance's accumulated `print` output (raw UTF-8 bytes) into `buf` (copy-out;
 * `out_len` gets the full length). The output only grows; a host reads incrementally by
 * tracking how many bytes it has already consumed.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_output(const struct DoodleInstance *instance,
                           uint8_t *buf,
                           uintptr_t cap,
                           uintptr_t *out_len);

/**
 * Copies the `index`-th dotted path segment of a parked `import` request (E§6) into `buf`
 * (copy-out; `out_len` gets the full byte length). E.g. `import shapes.circle` exposes
 * `"shapes"` at index 0 and `"circle"` at index 1 (`DoodleOutcome::request_count` segments).
 * `ErrContract` if the instance is not suspended on an import; `ErrIndexOutOfBounds` past the
 * last segment.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_import_path_segment(const struct DoodleInstance *instance,
                                        uint32_t index,
                                        uint8_t *buf,
                                        uintptr_t cap,
                                        uintptr_t *out_len);

/**
 * Resolves a parked `import` (E§6) with the module's `source` (UTF-8) under the host's
 * `canonical_id` (its singleton-cache identity, L§11.3), then drives on — the module's top
 * level runs before the importer continues. `ErrContract` if not suspended on an import;
 * `ErrInvalidUtf8` if either buffer is not UTF-8.
 *
 * # Safety
 * `instance` live; `source`/`canonical_id` point to their `*_len` readable bytes;
 * `out_outcome` writable.
 */
DoodleStatus doodle_resolve_import(struct DoodleInstance *instance,
                                   const uint8_t *source,
                                   uintptr_t source_len,
                                   const uint8_t *canonical_id,
                                   uintptr_t canonical_id_len,
                                   struct DoodleOutcome *out_outcome);

/**
 * Resolves a parked `import` (E§6) as **not found**: the engine raises `module-not-found` in
 * the importer (a multi-segment path first falls back to a member import, S-7), then drives
 * on. `ErrContract` if not suspended on an import.
 *
 * # Safety
 * `instance` live; `out_outcome` writable.
 */
DoodleStatus doodle_resolve_import_not_found(struct DoodleInstance *instance,
                                             struct DoodleOutcome *out_outcome);

/**
 * Resolves a parked `import` (E§6) by **raising** `value` at the `import` site (e.g. a failed
 * fetch), then drives on. `ErrContract` if not suspended on an import.
 *
 * # Safety
 * `instance` live; `out_outcome` writable.
 */
DoodleStatus doodle_resolve_import_raise(struct DoodleInstance *instance,
                                         DoodleHandle value,
                                         struct DoodleOutcome *out_outcome);

/**
 * Loads a program from UTF-8 `source` under `config`, writing a new instance to
 * `out_instance` on success (`DoodleStatus_Ok`). The host owns the returned instance and
 * frees it with [`doodle_free`]; `config` is not consumed (free it separately).
 *
 * On a lex/parse/resolve error the status is `DoodleStatus_ErrLoad` and the human-readable
 * error text is copied into `err_buf` (up to `err_buf_cap` bytes, always NUL-free UTF-8),
 * with the full byte length written to `out_err_len` (copy-out; a too-small buffer still
 * reports the needed length). `config` may be NULL (engine defaults).
 *
 * # Safety
 * `source` must point to `source_len` readable bytes; `out_instance` must be a writable
 * `*DoodleInstance`; `err_buf` may be NULL only if `err_buf_cap` is 0; `out_err_len` and
 * `config` may be NULL. Pointers must not alias in ways C forbids.
 */
DoodleStatus doodle_load(const uint8_t *source,
                         uintptr_t source_len,
                         const struct DoodleConfig *config,
                         struct DoodleInstance **out_instance,
                         uint8_t *err_buf,
                         uintptr_t err_buf_cap,
                         uintptr_t *out_err_len);

/**
 * Like [`doodle_load`] but with host extensions from `registry` (E§5.5) — capabilities and
 * built-ins the program can call. **Consumes** `registry` (moved into the instance): the
 * pointer is invalid after this call, whether it succeeds or fails; do not free or reuse it.
 *
 * # Safety
 * As [`doodle_load`], plus `registry` must be a pointer from `doodle_registry_new` not
 * already consumed/freed.
 */
DoodleStatus doodle_load_with_registry(const uint8_t *source,
                                       uintptr_t source_len,
                                       const struct DoodleConfig *config,
                                       struct DoodleRegistry *registry,
                                       struct DoodleInstance **out_instance,
                                       uint8_t *err_buf,
                                       uintptr_t err_buf_cap,
                                       uintptr_t *out_err_len);

/**
 * Frees an instance from [`doodle_load`], running the finalizer of every live foreign value
 * (E§3.1/§4.5). NULL is a no-op. After this the pointer is invalid.
 *
 * # Safety
 * `instance` must be a pointer from `doodle_load` that has not already been freed.
 */
void doodle_free(struct DoodleInstance *instance);

/**
 * Creates an empty registry. Returns NULL only on allocation failure. Populate it in the
 * order the host wants capability ids assigned (registration order is replay identity, §11),
 * then pass it to `doodle_load_with_registry` (which consumes it) — or free an unused one
 * with `doodle_registry_free`.
 */
struct DoodleRegistry *doodle_registry_new(void);

/**
 * Frees a registry created by `doodle_registry_new` that was **not** consumed by
 * `doodle_load_with_registry`. NULL is a no-op. Do not call this on a registry already
 * passed to `doodle_load_with_registry` (that consumed it).
 *
 * # Safety
 * `registry` must be a pointer from `doodle_registry_new` not already freed or consumed.
 */
void doodle_registry_free(struct DoodleRegistry *registry);

/**
 * Registers an engine built-in by identity (E§5.5), appending it to the registry. Returns
 * `DoodleStatus_ErrContract` if the name is already registered (a host bug — each built-in
 * registers at most once). No-op returning `ErrNullPointer` on a NULL registry.
 *
 * # Safety
 * `registry` must be a live pointer from `doodle_registry_new`.
 */
DoodleStatus doodle_registry_add_builtin(struct DoodleRegistry *registry, DoodleBuiltin builtin);

/**
 * Makes an `Int` from an `int64_t` (E§4.3). Larger magnitudes use `doodle_make_int_decimal`.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_make_int(struct DoodleInstance *instance, int64_t value, DoodleHandle *out);

/**
 * Makes an `Int` of any magnitude from a base-10 decimal string (E§4.3). `ErrMalformedInt`
 * if the text is not a base-10 integer literal.
 *
 * # Safety
 * `instance` live; `decimal` points to `decimal_len` readable bytes; `out` writable.
 */
DoodleStatus doodle_make_int_decimal(struct DoodleInstance *instance,
                                     const uint8_t *decimal,
                                     uintptr_t decimal_len,
                                     DoodleHandle *out);

/**
 * Makes a `Float` from a `double` (E§4.3); any NaN is canonicalized (E§11).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_make_float(struct DoodleInstance *instance, double value, DoodleHandle *out);

/**
 * Makes a `Bool` (E§4.1).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_make_bool(struct DoodleInstance *instance, bool value, DoodleHandle *out);

/**
 * Makes `nil` (E§4.9).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_make_nil(struct DoodleInstance *instance, DoodleHandle *out);

/**
 * Makes a `String` from UTF-8 bytes (E§4.4); the engine validates UTF-8 and normalizes to
 * NFC. `ErrInvalidUtf8` if the bytes are not well-formed UTF-8.
 *
 * # Safety
 * `instance` live; `bytes` points to `bytes_len` readable bytes; `out` writable.
 */
DoodleStatus doodle_make_string(struct DoodleInstance *instance,
                                const uint8_t *bytes,
                                uintptr_t bytes_len,
                                DoodleHandle *out);

/**
 * Makes a **foreign value** (E§4.5): an opaque host object Doodle can hold, pass, and store
 * by identity but not inspect. `tag` is the host's type discriminator; `ptr` is an opaque
 * token returned verbatim by `doodle_foreign_ptr` and handed to `finalizer`. A non-NULL
 * `finalizer` runs **exactly once** when the value dies (E§4.5); it receives only `ptr`, so it
 * cannot re-enter the engine, and must not unwind.
 *
 * # Safety
 * `instance` live; `out` writable; `finalizer` (if non-NULL) a valid function pointer.
 */
DoodleStatus doodle_make_foreign(struct DoodleInstance *instance,
                                 uint64_t tag,
                                 uint64_t ptr,
                                 struct Option_DoodleFinalizer finalizer,
                                 DoodleHandle *out);

/**
 * Writes a foreign value's host `tag` (E§4.5). `ErrWrongKind` if the handle is not a foreign
 * value; `ErrStaleHandle` if freed.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_foreign_tag(const struct DoodleInstance *instance,
                                DoodleHandle handle,
                                uint64_t *out);

/**
 * Writes a foreign value's opaque host `ptr` (E§4.5), returned verbatim. `ErrWrongKind` if
 * the handle is not a foreign value; `ErrStaleHandle` if freed.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_foreign_ptr(const struct DoodleInstance *instance,
                                DoodleHandle handle,
                                uint64_t *out);

/**
 * Reads an `Int` as `int64_t` (E§4.3). `ErrIntOutOfRange` for a bignum (read it with
 * `doodle_as_int_decimal`); `ErrWrongKind` for a non-int; `ErrStaleHandle` if freed.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_as_int(const struct DoodleInstance *instance,
                           DoodleHandle handle,
                           int64_t *out);

/**
 * Reads a `Float` as `double` (E§4.3).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_as_float(const struct DoodleInstance *instance,
                             DoodleHandle handle,
                             double *out);

/**
 * Reads a `Bool` (E§4.1).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_as_bool(const struct DoodleInstance *instance, DoodleHandle handle, bool *out);

/**
 * Writes whether the value is `nil` (E§4.9) — `ErrStaleHandle` if freed, never `ErrWrongKind`.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_is_nil(const struct DoodleInstance *instance, DoodleHandle handle, bool *out);

/**
 * Writes the value's kind (E§4.4). `ErrStaleHandle` if the handle is freed.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_kind_of(const struct DoodleInstance *instance,
                            DoodleHandle handle,
                            DoodleKind *out);

/**
 * Copies an `Int`'s value as a base-10 decimal string into `buf` (copy-out; `out_len` gets
 * the full length) — the arbitrary-precision counterpart of `doodle_as_int`.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_as_int_decimal(const struct DoodleInstance *instance,
                                   DoodleHandle handle,
                                   uint8_t *buf,
                                   uintptr_t cap,
                                   uintptr_t *out_len);

/**
 * Copies a `String`'s raw UTF-8 bytes into `buf` (copy-out; `out_len` gets the full byte
 * length). The engine keeps strings NFC, so these bytes are NFC UTF-8.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_string_bytes(const struct DoodleInstance *instance,
                                 DoodleHandle handle,
                                 uint8_t *buf,
                                 uintptr_t cap,
                                 uintptr_t *out_len);

/**
 * Releases a host-owned handle (E§4.2): decrements its reference count, freeing the slot at
 * zero. `ErrStaleHandle` if already freed. A handle must be released exactly as many times
 * as it was obtained.
 *
 * # Safety
 * `instance` must be a live pointer from `doodle_load`.
 */
DoodleStatus doodle_release(struct DoodleInstance *instance, DoodleHandle handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DOODLE_H */
