#ifndef DOODLE_H
#define DOODLE_H

/* Auto-generated by cbindgen; regenerate with scripts/capi-header.sh --write. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* The C ABI contract version (distinct from the engine version). See doodle_abi_version(). */
#define DOODLE_ABI_VERSION_MAJOR 0
#define DOODLE_ABI_VERSION_MINOR 1


/**
 * The result of a fallible C-ABI call: `Ok` on success, else the reason. Fallible calls
 * return this and write their result through an out-parameter (freeze convention 5).
 */
enum DoodleStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The call succeeded; any out-parameters are written.
   */
  DoodleStatus_Ok = 0,
  /**
   * A handle named a freed/reused slot — a use-after-release, forged, or (M7.6) a
   * cross-instance handle (mirrors `ValueError::Stale`).
   */
  DoodleStatus_ErrStaleHandle = 1,
  /**
   * A typed reader was applied to a value of a different kind (e.g. read an int from a
   * string). The value's actual kind is available via `doodle_kind_of`.
   */
  DoodleStatus_ErrWrongKind = 2,
  /**
   * `doodle_as_int` on an integer whose magnitude exceeds `int64_t` (a bignum — read it
   * with `doodle_as_int_decimal`).
   */
  DoodleStatus_ErrIntOutOfRange = 3,
  /**
   * A list/string index was past the end.
   */
  DoodleStatus_ErrIndexOutOfBounds = 4,
  /**
   * `doodle_make_string` was given bytes that are not well-formed UTF-8.
   */
  DoodleStatus_ErrInvalidUtf8 = 5,
  /**
   * `doodle_make_int_decimal` was given text that is not a base-10 integer literal.
   */
  DoodleStatus_ErrMalformedInt = 6,
  /**
   * The config named a Unicode version the engine does not support (S-41).
   */
  DoodleStatus_ErrUnsupportedUnicode = 7,
  /**
   * The program failed to load: a lex/parse/resolve error (its text is copied into
   * `doodle_load`'s `err_buf`).
   */
  DoodleStatus_ErrLoad = 8,
  /**
   * A caller buffer was too small; the required length is written to the `needed`
   * out-parameter and the buffer is left untouched (copy-out, freeze convention 4).
   */
  DoodleStatus_ErrBufferTooSmall = 9,
  /**
   * A required pointer argument was NULL.
   */
  DoodleStatus_ErrNullPointer = 10,
  /**
   * A host-contract violation the engine caught (e.g. resolving a non-suspended instance).
   */
  DoodleStatus_ErrContract = 11,
  /**
   * A Rust panic was caught at the boundary (an engine bug; the firewall of last resort,
   * [`crate::guard`]). The instance should be considered unusable.
   */
  DoodleStatus_ErrPanic = 12,
  /**
   * A pause-scoped observation read used a **stale generation** token: a `drive`/`resolve`
   * advanced the stack since the token was obtained (D-M7-12). **Benign and expected** — the
   * host re-walks the stack (`doodle_stack_frame_count`) and retries — NOT a contract
   * violation (`ErrContract`) and distinct from `ErrStaleHandle` (a released/forged handle).
   */
  DoodleStatus_ErrStale = 13,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleStatus DoodleStatus;
#else
typedef uint32_t DoodleStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The outcome of a host-invoked reentrant block (`doodle_call_block`, E§5.4/§7.6) — the C
 * mirror of the core `BlockOutcome`. On `NonLocalExit` or `Halted` the host callback **must
 * return promptly with no result**; the engine's apply-site backstop (S-46/S-15) faults a
 * host that drives on regardless, so a violation is a defined `Faulted`, never UB.
 */
enum DoodleBlockOutcome
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The block completed (fell off its end, or `continue`d).
   */
  DoodleBlockOutcome_Completed = 0,
  /**
   * A `break`/`return`/raise exited the block across the host boundary; it is parked for
   * the call site to resume once the callback returns.
   */
  DoodleBlockOutcome_NonLocalExit = 1,
  /**
   * A fault parked (a limit, the S-15 `NestedSuspend`, or a stale block-argument handle);
   * the drive surfaces it once the callback returns.
   */
  DoodleBlockOutcome_Halted = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleBlockOutcome DoodleBlockOutcome;
#else
typedef uint32_t DoodleBlockOutcome;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A value's kind (E§4.4), the C mirror of `doodle_core`'s `Kind`.
 */
enum DoodleKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * `nil` (L§4.9).
   */
  DoodleKind_Nil = 0,
  /**
   * A boolean (L§4.1).
   */
  DoodleKind_Bool = 1,
  /**
   * An integer of any magnitude (L§4.2).
   */
  DoodleKind_Int = 2,
  /**
   * A float (L§4.3).
   */
  DoodleKind_Float = 3,
  /**
   * A string (L§4.4).
   */
  DoodleKind_String = 4,
  /**
   * A byte string (L§4.5).
   */
  DoodleKind_Bytes = 5,
  /**
   * A list (L§4.6).
   */
  DoodleKind_List = 6,
  /**
   * A dict (L§4.7).
   */
  DoodleKind_Dict = 7,
  /**
   * A record (L§4.14).
   */
  DoodleKind_Record = 8,
  /**
   * A callable (L§6).
   */
  DoodleKind_Callable = 9,
  /**
   * A module value (L§9).
   */
  DoodleKind_Module = 10,
  /**
   * A type value (L§4.12).
   */
  DoodleKind_Type = 11,
  /**
   * A foreign (host) value (E§4.5).
   */
  DoodleKind_Foreign = 12,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleKind DoodleKind;
#else
typedef uint32_t DoodleKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The observation-mode granularity (E§8.8): per-statement (default) or per-subexpression.
 */
enum DoodleObservationMode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Per-statement safe points only (the default).
   */
  DoodleObservationMode_Statement = 0,
  /**
   * Adds per-subexpression fine safe points (the "watch your expression evaluate" mode).
   */
  DoodleObservationMode_Subexpression = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleObservationMode DoodleObservationMode;
#else
typedef uint32_t DoodleObservationMode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Whether a host foreign function is a procedure (`to`, yields Void) or a function (`fn`,
 * yields a value) — the C mirror of the core `BodyKind` a foreign descriptor takes
 * (`doodle_foreign_desc_new`).
 */
enum DoodleBodyKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A procedure (`to`): yields no value; its call is a statement (L§8.4).
   */
  DoodleBodyKind_Proc = 0,
  /**
   * A function (`fn`): yields a value the call consumes.
   */
  DoodleBodyKind_Func = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleBodyKind DoodleBodyKind;
#else
typedef uint32_t DoodleBodyKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A driving directive (E§7.3): how far to run before returning to the host.
 */
enum DoodleDirective
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Run to the next capability / raise / fault / completion (a fast run).
   */
  DoodleDirective_RunToCompletion = 0,
  /**
   * Like `RunToCompletion` but also stop at breakpoints and the raise-trap.
   */
  DoodleDirective_Continue = 1,
  /**
   * Stop at the next safe point, in any frame (synonym of `StepInto`).
   */
  DoodleDirective_Step = 2,
  /**
   * Step, descending into calls.
   */
  DoodleDirective_StepInto = 3,
  /**
   * Step, treating a call as one step.
   */
  DoodleDirective_StepOver = 4,
  /**
   * Run until the current frame returns.
   */
  DoodleDirective_StepOut = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleDirective DoodleDirective;
#else
typedef uint32_t DoodleDirective;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which kind of stop a drive reached (E§7.2) — the tag of [`DoodleOutcome`].
 */
enum DoodleOutcomeKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The driven unit finished (`DoodleOutcome::value` is its result, `0` for Void).
   */
  DoodleOutcomeKind_Completed = 0,
  /**
   * A capability must be fulfilled before continuing (`capability`/`request_count`;
   * the arg marshalling is M7.2).
   */
  DoodleOutcomeKind_Suspended = 1,
  /**
   * An `import` reached an unloaded module (`request_count` path segments; the resolver
   * is M7.2).
   */
  DoodleOutcomeKind_SuspendedImport = 2,
  /**
   * Stopped at a safe point (`pause_reason`; `breakpoint_id` when a breakpoint).
   */
  DoodleOutcomeKind_Paused = 3,
  /**
   * An uncaught exception reached the boundary (E§9); `span_*` is its site. Read its
   * described form with `doodle_raised_kind` / `doodle_raised_message`.
   */
  DoodleOutcomeKind_Raised = 4,
  /**
   * A non-resumable engine fault (`fault`).
   */
  DoodleOutcomeKind_Faulted = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleOutcomeKind DoodleOutcomeKind;
#else
typedef uint32_t DoodleOutcomeKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Why a drive paused (E§7.2).
 */
enum DoodlePauseReason
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The active `Step*` directive reached its next safe point.
   */
  DoodlePauseReason_Step = 0,
  /**
   * A breakpoint was hit (`DoodleOutcome::breakpoint_id`).
   */
  DoodlePauseReason_Breakpoint = 1,
  /**
   * A raise was trapped before propagating (E§8.7).
   */
  DoodlePauseReason_RaiseTrap = 2,
  /**
   * The host requested a pause (E§8.8).
   */
  DoodlePauseReason_HostPause = 3,
  /**
   * The drive's bounded-run fuel was spent (S-40) — a resumable slice boundary; re-drive.
   */
  DoodlePauseReason_SliceEnd = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodlePauseReason DoodlePauseReason;
#else
typedef uint32_t DoodlePauseReason;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A non-resumable engine fault (E§7.2/§10). The core's `LimitExceeded(LimitKind)` is
 * flattened into distinct `Limit*` codes (as the wasm surface flattens to string tags).
 */
enum DoodleFault
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The step budget was exhausted (E§10.2).
   */
  DoodleFault_LimitStepBudget = 0,
  /**
   * The heap-byte ceiling was exceeded (E§10.2).
   */
  DoodleFault_LimitHeap = 1,
  /**
   * The non-tail stack-depth limit was exceeded (E§10.2).
   */
  DoodleFault_LimitStackDepth = 2,
  /**
   * The tail-history bound was exceeded (E§8.3).
   */
  DoodleFault_LimitTailHistory = 3,
  /**
   * A single op's result would exceed the per-op result cap (the latency rail, E§10.2).
   */
  DoodleFault_LimitOpResult = 4,
  /**
   * The host cancelled the drive (E§10.1).
   */
  DoodleFault_Cancelled = 5,
  /**
   * A suspending capability was reached inside a foreign/native callback (E§5.4, S-15).
   */
  DoodleFault_NestedSuspend = 6,
  /**
   * An internal invariant was violated (an engine bug).
   */
  DoodleFault_Internal = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleFault DoodleFault;
#else
typedef uint32_t DoodleFault;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a module-level global is (L§5), the C mirror of the resolver's `GlobalKind` — so a host
 * filters a module's globals (e.g. show `Let`/`Const`/`Parameter` as data, hide `Proc`/`Fn`).
 */
enum DoodleGlobalKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A mutable binding (`let`).
   */
  DoodleGlobalKind_Let = 0,
  /**
   * A non-reassignable binding (`const`).
   */
  DoodleGlobalKind_Const = 1,
  /**
   * A dynamic parameter (`parameter`).
   */
  DoodleGlobalKind_Parameter = 2,
  /**
   * A procedure (`to`).
   */
  DoodleGlobalKind_Proc = 3,
  /**
   * A function (`fn`).
   */
  DoodleGlobalKind_Func = 4,
  /**
   * A record type (`record`/`ref record`).
   */
  DoodleGlobalKind_Record = 5,
  /**
   * A protocol (`protocol`).
   */
  DoodleGlobalKind_Protocol = 6,
  /**
   * A nested module (`module`).
   */
  DoodleGlobalKind_Module = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleGlobalKind DoodleGlobalKind;
#else
typedef uint32_t DoodleGlobalKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * An engine-provided built-in intrinsic a host can register by identity (E§5.5), without
 * supplying a callback. The synchronous ones (`Print`/`Length`/…) run inline; the
 * capabilities (`ReadLine`/`DrawLine`/`SetTurtle`/`ClearCanvas`) suspend to the host.
 */
enum DoodleBuiltin
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * `print(value)` — renders a value and a newline to the output sink (synchronous).
   */
  DoodleBuiltin_Print = 0,
  /**
   * `length(x)` — the length of a string/list/dict/bytes (synchronous).
   */
  DoodleBuiltin_Length = 1,
  /**
   * `each(list) do (x) … end` — a native block-consumer (synchronous, reentrant).
   */
  DoodleBuiltin_Each = 2,
  /**
   * `encode(string) -> bytes` — UTF-8 encode (synchronous).
   */
  DoodleBuiltin_Encode = 3,
  /**
   * `decode(bytes) -> string` — UTF-8 decode (synchronous).
   */
  DoodleBuiltin_Decode = 4,
  /**
   * `read_line() -> string` — a suspending input capability.
   */
  DoodleBuiltin_ReadLine = 5,
  /**
   * `sin(x) -> float` (synchronous, deterministic libm).
   */
  DoodleBuiltin_Sin = 6,
  /**
   * `cos(x) -> float` (synchronous, deterministic libm).
   */
  DoodleBuiltin_Cos = 7,
  /**
   * `draw_line(x0,y0,x1,y1,r,g,b,a)` — a suspending turtle capability.
   */
  DoodleBuiltin_DrawLine = 8,
  /**
   * `set_turtle(x,y,heading,visible)` — a suspending turtle capability.
   */
  DoodleBuiltin_SetTurtle = 9,
  /**
   * `clear_canvas()` — a suspending turtle capability.
   */
  DoodleBuiltin_ClearCanvas = 10,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum DoodleBuiltin DoodleBuiltin;
#else
typedef uint32_t DoodleBuiltin;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The re-entry context handed to a host foreign callback (opaque to C). Wraps the raw
 * `&mut IntrinsicCtx` the engine threaded down plus the callback's pending reply. **Valid only
 * while it is the innermost active callback** — its validity is tracked by [`CURRENT_CTX`], not
 * a field, so use-after-return and reentrant-ancestor use are both a defined `ErrContract`.
 */
typedef struct DoodleCallCtx DoodleCallCtx;

/**
 * An opaque instance configuration under construction. Built with `doodle_config_new`,
 * mutated with the `doodle_config_set_*` setters, consumed by `doodle_load`, and released
 * with `doodle_config_free`.
 */
typedef struct DoodleConfig DoodleConfig;

/**
 * A host foreign-function descriptor under construction (E§5.1). Built with
 * `doodle_foreign_desc_new`, filled with the `doodle_foreign_desc_*` builders, then
 * **consumed** by `doodle_registry_add_foreign` (or discarded with `doodle_foreign_desc_free`).
 * Opaque to C.
 */
typedef struct DoodleForeignDesc DoodleForeignDesc;

/**
 * A loaded Doodle program: the engine [`Instance`] plus a little host-facing state — the
 * described form of its most recent uncaught raise (for `doodle_raised_kind`/`_message`) and
 * the bound argument handles of a parked capability request (for `doodle_capability_arg`).
 * Opaque to C.
 */
typedef struct DoodleInstance DoodleInstance;

/**
 * A host-extension registry under construction (E§5.5). Built with `doodle_registry_new`,
 * populated in order with `doodle_registry_add_builtin`, then **consumed** by
 * `doodle_load_with_registry`. Opaque to C.
 */
typedef struct DoodleRegistry DoodleRegistry;

typedef struct Option_DoodleFinalizer Option_DoodleFinalizer;

/**
 * An opaque, per-instance value handle (E§4.2), crossing the ABI as a plain `uint64_t`.
 * Round-trips the engine's internal `Handle` bits; the host treats it as opaque and must
 * [`doodle_release`](crate::value::doodle_release) handles it no longer needs. `0` is the
 * reserved null handle (no value), never a live handle.
 */
typedef uint64_t DoodleHandle;

/**
 * A C host foreign-function callback (E§5.2): given a [`DoodleCallCtx`] (valid only for the
 * call's dynamic extent) and its registered `user_data`, it reads arguments, may invoke its
 * block, and reports a result/raise via `doodle_call_set_result`/`doodle_call_set_raise`.
 * Returns `DoodleStatus_Ok` on success; a non-`Ok` return (or a panic) faults the drive
 * `Internal` — a Doodle-level error is a *raise* (`doodle_call_set_raise`), not a status.
 */
typedef DoodleStatus (*DoodleForeignFn)(struct DoodleCallCtx *ctx, void *user_data);

/**
 * The result of a drive (E§7.2), written by `doodle_drive`/`doodle_resolve`. A flat
 * `#[repr(C)]` struct (not a union — a union in a frozen header cannot grow safely): each
 * field is meaningful only for the `kind`s named in its doc, others are `0`/false. The
 * `reserved` tail is growth room — a future field claims a reserved slot without changing
 * the struct's size or layout (freeze convention 2).
 */
typedef struct DoodleOutcome {
  /**
   * Which stop was reached (the tag).
   */
  DoodleOutcomeKind kind;
  /**
   * `Paused`: why.
   */
  DoodlePauseReason pause_reason;
  /**
   * `Faulted`: which fault.
   */
  DoodleFault fault;
  /**
   * `Paused` + `pause_reason == Breakpoint`: the breakpoint id.
   */
  uint32_t breakpoint_id;
  /**
   * `Suspended`: the capability id. `SuspendedImport`: the importing module id.
   */
  uint32_t capability;
  /**
   * `Suspended`: the number of bound argument handles. `SuspendedImport`: the number of
   * dotted path segments. (The M7.2 accessors read the elements.)
   */
  uint32_t request_count;
  /**
   * `Raised`: whether `span_start`/`span_end` name the raising site.
   */
  bool has_span;
  /**
   * `Raised`: the raising site's start byte offset (when `has_span`).
   */
  uint32_t span_start;
  /**
   * `Raised`: the raising site's end byte offset (when `has_span`).
   */
  uint32_t span_end;
  /**
   * `Completed`: the result value (`0` for Void; a reentrant `fn` return populates it once
   * the boundary can intern one, M7.3). A **host-owned** handle when non-zero —
   * `doodle_release` it. `0` for every other kind (a raised value is read in described form
   * via `doodle_raised_kind`/`_message`).
   */
  DoodleHandle value;
  /**
   * Reserved for additive growth (freeze convention 2); always written as `0`.
   */
  uint64_t reserved[4];
} DoodleOutcome;

/**
 * A source position (E§8.1): a byte span into a module's NFC source plus an **opaque
 * instance-scoped module token** (D-M7-14). Equal `module` tokens ⇔ the same module within one
 * instance (stable for its lifetime), and nothing more — it is **not** a documented index;
 * resolve it to the host's canonical id with `doodle_module_canonical_id`. The host maps the
 * byte span to 1-based line/column using the source it holds (the engine exposes positions, not
 * text).
 */
typedef struct DoodlePosition {
  /**
   * The construct's start byte offset into the module's NFC source.
   */
  uint32_t span_start;
  /**
   * The construct's end byte offset.
   */
  uint32_t span_end;
  /**
   * The opaque module token (see the type doc).
   */
  uint32_t module;
} DoodlePosition;

/**
 * One live stack frame (E§8.2), filled by `doodle_frame_at` — pure data; the callable is minted
 * separately by `doodle_frame_callable` (D-M7-13). Innermost frame is index 0. The `reserved`
 * tail is additive growth room (freeze convention 2).
 */
typedef struct DoodleFrame {
  /**
   * Whether this frame runs a callable value (get it via `doodle_frame_callable`); `false` for
   * the module top level and `do … end` block frames.
   */
  bool has_callable;
  /**
   * Whether `call_site` names where this frame was entered (`false` for the module top level
   * or a block invoked by native host code).
   */
  bool has_call_site;
  /**
   * Where this frame was entered — meaningful only when `has_call_site`.
   */
  struct DoodlePosition call_site;
  /**
   * Tail-iterations absorbed into this frame by proper-tail-call reuse (E§8.3): `0` for a
   * fresh frame, `n` after `n` tail calls reused the same slot.
   */
  uint64_t tail_count;
  /**
   * The frame's home module, as an opaque module token (see [`DoodlePosition::module`]).
   */
  uint32_t module;
  /**
   * Reserved for additive growth (freeze convention 2); always written as `0`.
   */
  uint64_t reserved[4];
} DoodleFrame;

/**
 * One module-level global (E§8.2, L§5), filled by `doodle_module_global` — its `kind` and the
 * `decl_span` of its declaration. Its name copies out separately (`doodle_module_global_name`)
 * and its current value is fetched by the same index (`doodle_module_global_value`). The
 * `reserved` tail is additive growth room (freeze convention 2).
 */
typedef struct DoodleGlobal {
  /**
   * What kind of declaration the global is.
   */
  DoodleGlobalKind kind;
  /**
   * The source position of the declaration.
   */
  struct DoodlePosition decl_span;
  /**
   * Reserved for additive growth; always written as `0`.
   */
  uint64_t reserved[2];
} DoodleGlobal;

/**
 * The null handle: the absence of a value (a `to`/module result, an empty outcome slot).
 */
#define DOODLE_NULL_HANDLE 0

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the Doodle engine version as a NUL-terminated C string.
 *
 * The returned pointer is valid for the lifetime of the program and must not
 * be freed by the caller.
 */
const char *doodle_version(void);

/**
 * Returns the C ABI contract version as `(major << 16) | minor` — distinct from the
 * engine version ([`doodle_version`]). A host compiled against `doodle.h` compares this
 * against the header's `DOODLE_ABI_VERSION_MAJOR`/`_MINOR` at load: a differing **major**
 * is incompatible; a newer **minor** is backward-compatible (additive only).
 */
uint32_t doodle_abi_version(void);

/**
 * Writes the number of bound (non-block) arguments this call received (E§5.2) — read each with
 * [`doodle_call_arg`]. `ErrContract` unless `ctx` is the innermost active callback.
 *
 * # Safety
 * `ctx` must be the callback's current `DoodleCallCtx`; `out` writable.
 */
DoodleStatus doodle_call_arg_count(struct DoodleCallCtx *ctx, uint32_t *out);

/**
 * Interns the `index`-th bound argument as a fresh **host-owned** handle (E§4.2) and writes it
 * to `out`; the host reads it with the ordinary `doodle_as_*` and `doodle_release`s it.
 * `ErrIndexOutOfBounds` past the last argument; `ErrContract` unless `ctx` is the innermost call.
 *
 * # Safety
 * `ctx` must be the callback's current `DoodleCallCtx`; `out` writable.
 */
DoodleStatus doodle_call_arg(struct DoodleCallCtx *ctx, uint32_t index, DoodleHandle *out);

/**
 * Invokes this call's received block **reentrantly** (E§5.4/§7.6) with the `n` argument handles
 * at `args`, writing the [`DoodleBlockOutcome`] to `out`. On `NonLocalExit`/`Halted` the
 * callback **must return promptly with no result**. Routes through
 * [`IntrinsicCtx::invoke_block_handles`] (never a second `&mut Instance`). `ErrContract` unless
 * `ctx` is the innermost active callback.
 *
 * # Safety
 * `ctx` must be the callback's current `DoodleCallCtx`; `args` points to `n` readable handles (or
 * NULL when `n` is 0); `out` writable.
 */
DoodleStatus doodle_call_block(struct DoodleCallCtx *ctx,
                               const DoodleHandle *args,
                               uint32_t n,
                               DoodleBlockOutcome *out);

/**
 * Appends `len` bytes at `bytes` to the instance's output sink (the same sink `print` writes,
 * read via `doodle_output`). `ErrContract` unless `ctx` is the innermost active callback.
 *
 * # Safety
 * `ctx` must be the callback's current `DoodleCallCtx`; `bytes` points to `len` readable bytes (or
 * NULL when `len` is 0).
 */
DoodleStatus doodle_call_emit(struct DoodleCallCtx *ctx, const uint8_t *bytes, uintptr_t len);

/**
 * Sets this `fn` call's result to the value named by `handle` (E§5.2) — the value the call
 * yields. A `to` sets nothing (leaving Void). **Consumes `handle`**: the engine resolves it and
 * releases it after the callback returns, so the host must not release or reuse it afterward.
 * `ErrContract` unless `ctx` is the innermost active callback.
 *
 * # Safety
 * `ctx` must be the callback's current `DoodleCallCtx`.
 */
DoodleStatus doodle_call_set_result(struct DoodleCallCtx *ctx, DoodleHandle handle);

/**
 * Raises the value named by `handle` at this call site (E§5.2/§7.5), like a capability's
 * `resolve` raise — the value *is* the exception (a program `rescue e` binds it as-is). The
 * callback should then return `DoodleStatus_Ok`. **Consumes `handle`** (as
 * `doodle_call_set_result` does): do not release or reuse it. `ErrContract` unless `ctx` is
 * the innermost active callback.
 *
 * # Safety
 * `ctx` must be the callback's current `DoodleCallCtx`.
 */
DoodleStatus doodle_call_set_raise(struct DoodleCallCtx *ctx, DoodleHandle handle);

/**
 * Writes the value's kind (E§4.4). `ErrStaleHandle` if the handle is freed.
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_kind_of(struct DoodleCallCtx *ctx, DoodleHandle handle, DoodleKind *out);

/**
 * Reads an `Int` as `int64_t` (E§4.3). `ErrIntOutOfRange` for a bignum; `ErrWrongKind` otherwise.
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_as_int(struct DoodleCallCtx *ctx, DoodleHandle handle, int64_t *out);

/**
 * Reads a `Float` as `double` (E§4.3).
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_as_float(struct DoodleCallCtx *ctx, DoodleHandle handle, double *out);

/**
 * Reads a `Bool` (E§4.1).
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_as_bool(struct DoodleCallCtx *ctx, DoodleHandle handle, bool *out);

/**
 * Writes whether the value is `nil` (E§4.9) — `ErrStaleHandle` if freed, never `ErrWrongKind`.
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_is_nil(struct DoodleCallCtx *ctx, DoodleHandle handle, bool *out);

/**
 * Writes the number of elements in a list (E§4.6). `ErrWrongKind` if not a list.
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_list_length(struct DoodleCallCtx *ctx,
                                     DoodleHandle handle,
                                     uintptr_t *out);

/**
 * Writes a foreign value's host `tag` (E§4.5). `ErrWrongKind` if not a foreign value.
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_foreign_tag(struct DoodleCallCtx *ctx, DoodleHandle handle, uint64_t *out);

/**
 * Writes a foreign value's opaque host `ptr` (E§4.5), verbatim. `ErrWrongKind` if not a foreign.
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_foreign_ptr(struct DoodleCallCtx *ctx, DoodleHandle handle, uint64_t *out);

/**
 * Copies an `Int`'s value as base-10 decimal into `buf` (copy-out; `out_len` gets the full
 * length) — the arbitrary-precision counterpart of [`doodle_call_as_int`].
 *
 * # Safety
 * `ctx` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_call_as_int_decimal(struct DoodleCallCtx *ctx,
                                        DoodleHandle handle,
                                        uint8_t *buf,
                                        uintptr_t cap,
                                        uintptr_t *out_len);

/**
 * Copies a `String`'s NFC UTF-8 bytes into `buf` (copy-out; `out_len` gets the full byte length).
 *
 * # Safety
 * `ctx` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_call_string_bytes(struct DoodleCallCtx *ctx,
                                      DoodleHandle handle,
                                      uint8_t *buf,
                                      uintptr_t cap,
                                      uintptr_t *out_len);

/**
 * Copies a byte string's raw bytes into `buf` (copy-out; `out_len` gets the full length).
 *
 * # Safety
 * `ctx` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_call_as_bytes(struct DoodleCallCtx *ctx,
                                  DoodleHandle handle,
                                  uint8_t *buf,
                                  uintptr_t cap,
                                  uintptr_t *out_len);

/**
 * Releases a handle the callback obtained (E§4.2): an arg handle from `doodle_call_arg` or a
 * value it constructed. `ErrStaleHandle` if already freed. Release each exactly once.
 *
 * # Safety
 * `ctx` the callback's current `DoodleCallCtx`.
 */
DoodleStatus doodle_call_release(struct DoodleCallCtx *ctx, DoodleHandle handle);

/**
 * Constructs an integer (E§4.3) on the callback's ctx.
 *
 * # Safety
 * `ctx` the callback's current `DoodleCallCtx`; `out` writable.
 */
DoodleStatus doodle_call_make_int(struct DoodleCallCtx *ctx, int64_t value, DoodleHandle *out);

/**
 * Constructs an integer of any magnitude from base-10 `decimal` (E§4.3). `ErrMalformedInt` if
 * the text is not a base-10 integer literal.
 *
 * # Safety
 * `ctx` live; `decimal` points to `decimal_len` readable bytes; `out` writable.
 */
DoodleStatus doodle_call_make_int_decimal(struct DoodleCallCtx *ctx,
                                          const uint8_t *decimal,
                                          uintptr_t decimal_len,
                                          DoodleHandle *out);

/**
 * Constructs a float (E§4.3); any NaN is canonicalized (E§11).
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_make_float(struct DoodleCallCtx *ctx, double value, DoodleHandle *out);

/**
 * Constructs a boolean (E§4.1).
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_make_bool(struct DoodleCallCtx *ctx, bool value, DoodleHandle *out);

/**
 * Constructs `nil` (E§4.9).
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_make_nil(struct DoodleCallCtx *ctx, DoodleHandle *out);

/**
 * Constructs a string from UTF-8 `bytes` (E§4.4): validated + NFC-normalized. `ErrInvalidUtf8`
 * if the bytes are not well-formed UTF-8.
 *
 * # Safety
 * `ctx` live; `bytes` points to `bytes_len` readable bytes (or NULL with 0); `out` writable.
 */
DoodleStatus doodle_call_make_string(struct DoodleCallCtx *ctx,
                                     const uint8_t *bytes,
                                     uintptr_t bytes_len,
                                     DoodleHandle *out);

/**
 * Constructs a byte string (E§4.5): raw bytes, no encoding or normalization.
 *
 * # Safety
 * `ctx` live; `bytes` points to `bytes_len` readable bytes (or NULL with 0); `out` writable.
 */
DoodleStatus doodle_call_make_bytes(struct DoodleCallCtx *ctx,
                                    const uint8_t *bytes,
                                    uintptr_t bytes_len,
                                    DoodleHandle *out);

/**
 * Constructs an empty list (E§4.6); grow it with [`doodle_call_list_append`].
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_make_list(struct DoodleCallCtx *ctx, DoodleHandle *out);

/**
 * Appends the value `value` to the list `list` (E§4.6). `ErrWrongKind` if `list` is not a list.
 *
 * # Safety
 * `ctx` the callback's current `DoodleCallCtx`.
 */
DoodleStatus doodle_call_list_append(struct DoodleCallCtx *ctx,
                                     DoodleHandle list,
                                     DoodleHandle value);

/**
 * Constructs a foreign (host) value (E§4.5): an opaque `tag`/`ptr` with an exactly-once
 * `finalizer` (which receives only `ptr` and must not unwind).
 *
 * # Safety
 * `ctx` live; `out` writable; `finalizer` (if non-NULL) a valid function pointer.
 */
DoodleStatus doodle_call_make_foreign(struct DoodleCallCtx *ctx,
                                      uint64_t tag,
                                      uint64_t ptr,
                                      struct Option_DoodleFinalizer finalizer,
                                      DoodleHandle *out);

/**
 * A fresh **host-owned** handle to the element at `index` of a list (E§4.6). `ErrWrongKind` if
 * not a list; `ErrIndexOutOfBounds` past the end.
 *
 * # Safety
 * `ctx` live; `out` writable.
 */
DoodleStatus doodle_call_list_get(struct DoodleCallCtx *ctx,
                                  DoodleHandle list,
                                  uintptr_t index,
                                  DoodleHandle *out);

/**
 * Creates a config with the engine defaults (E§3.1): default limits, statement-granularity
 * observation, and the engine's pinned Unicode version. Returns NULL only on allocation
 * failure. Free it with `doodle_config_free` (loading does not consume it).
 */
struct DoodleConfig *doodle_config_new(void);

/**
 * Frees a config created by `doodle_config_new`. NULL is a no-op. The config is the host's
 * to free whether or not it was passed to `doodle_load` (load copies what it needs).
 *
 * # Safety
 * `config` must be a pointer returned by `doodle_config_new` and not already freed.
 */
void doodle_config_free(struct DoodleConfig *config);

/**
 * Sets the resource limits (E§10.2): the step budget, heap-byte ceiling, non-tail stack
 * depth, and the per-operation result-size cap (the latency rail — `UINT64_MAX` disables
 * it). No-op on a NULL config.
 *
 * # Safety
 * `config` must be a live pointer from `doodle_config_new` (or NULL).
 */
void doodle_config_set_limits(struct DoodleConfig *config,
                              uint64_t step_budget,
                              uint64_t heap_bytes,
                              uint32_t stack_depth,
                              uint64_t max_op_result_bytes);

/**
 * Sets the observation-mode granularity (E§8.8). No-op on a NULL config.
 *
 * # Safety
 * `config` must be a live pointer from `doodle_config_new` (or NULL).
 */
void doodle_config_set_observation_mode(struct DoodleConfig *config, DoodleObservationMode mode);

/**
 * Sets the **target Unicode version** the host expects (S-41, the replay guard): a
 * recording made under one UCD version fails to load under another rather than diverging
 * silently on grapheme/normalization behavior (E§11). A `major` of `0` clears it (use the
 * engine's pinned version). No-op on a NULL config.
 *
 * # Safety
 * `config` must be a live pointer from `doodle_config_new` (or NULL).
 */
void doodle_config_set_target_unicode(struct DoodleConfig *config,
                                      uint16_t major,
                                      uint16_t minor,
                                      uint16_t micro);

/**
 * Creates a foreign-function descriptor for a function named `name` (UTF-8) of `kind`. Returns
 * NULL on allocation failure, a NULL name (with a non-zero length), or a non-UTF-8 name.
 * Populate it with the `doodle_foreign_desc_*` builders (in the parameter order wanted), then
 * pass it to `doodle_registry_add_foreign` (which consumes it) or free it with
 * `doodle_foreign_desc_free`.
 *
 * # Safety
 * `name` must point to `name_len` readable bytes (or be NULL with `name_len` 0).
 */
struct DoodleForeignDesc *doodle_foreign_desc_new(const uint8_t *name,
                                                  uintptr_t name_len,
                                                  DoodleBodyKind kind);

/**
 * Appends a **required** ordinary parameter `name` (L§8.3).
 *
 * # Safety
 * `desc` a live descriptor; `name` points to `name_len` readable bytes (or NULL with 0).
 */
DoodleStatus doodle_foreign_desc_param(struct DoodleForeignDesc *desc,
                                       const uint8_t *name,
                                       uintptr_t name_len);

/**
 * Appends the **trailing block** parameter `name` (L§8.2): a `do … end` the callback invokes
 * reentrantly (`doodle_call_block`).
 *
 * # Safety
 * `desc` a live descriptor; `name` points to `name_len` readable bytes (or NULL with 0).
 */
DoodleStatus doodle_foreign_desc_block_param(struct DoodleForeignDesc *desc,
                                             const uint8_t *name,
                                             uintptr_t name_len);

/**
 * Appends an ordinary parameter `name` with an integer default (L§8.3, D-M7-8).
 *
 * # Safety
 * `desc` a live descriptor; `name` points to `name_len` readable bytes (or NULL with 0).
 */
DoodleStatus doodle_foreign_desc_default_int(struct DoodleForeignDesc *desc,
                                             const uint8_t *name,
                                             uintptr_t name_len,
                                             int64_t value);

/**
 * Appends an ordinary parameter `name` with a float default (L§8.3, D-M7-8). Any NaN is
 * canonicalized when the recipe materializes (S-28).
 *
 * # Safety
 * `desc` a live descriptor; `name` points to `name_len` readable bytes (or NULL with 0).
 */
DoodleStatus doodle_foreign_desc_default_float(struct DoodleForeignDesc *desc,
                                               const uint8_t *name,
                                               uintptr_t name_len,
                                               double value);

/**
 * Appends an ordinary parameter `name` with a boolean default (L§8.3, D-M7-8).
 *
 * # Safety
 * `desc` a live descriptor; `name` points to `name_len` readable bytes (or NULL with 0).
 */
DoodleStatus doodle_foreign_desc_default_bool(struct DoodleForeignDesc *desc,
                                              const uint8_t *name,
                                              uintptr_t name_len,
                                              bool value);

/**
 * Appends an ordinary parameter `name` with a `nil` default (L§8.3, D-M7-8).
 *
 * # Safety
 * `desc` a live descriptor; `name` points to `name_len` readable bytes (or NULL with 0).
 */
DoodleStatus doodle_foreign_desc_default_nil(struct DoodleForeignDesc *desc,
                                             const uint8_t *name,
                                             uintptr_t name_len);

/**
 * Appends an ordinary parameter `name` with a **string** default (L§8.3, D-M7-8) from UTF-8
 * `value` bytes: validated (`ErrInvalidUtf8`) and NFC-normalized (the untrusted-boundary
 * counterpart of `make_string`, upholding the NFC contract for `ConstValue::Str`).
 *
 * # Safety
 * `desc` a live descriptor; `name`/`value` point to their `*_len` readable bytes (NULL allowed
 * only with a 0 length).
 */
DoodleStatus doodle_foreign_desc_default_string(struct DoodleForeignDesc *desc,
                                                const uint8_t *name,
                                                uintptr_t name_len,
                                                const uint8_t *value,
                                                uintptr_t value_len);

/**
 * Appends an ordinary parameter `name` with a **byte-string** default (L§8.3, D-M7-8) from the
 * raw `value` bytes (no encoding or normalization).
 *
 * # Safety
 * `desc` a live descriptor; `name`/`value` point to their `*_len` readable bytes (NULL allowed
 * only with a 0 length).
 */
DoodleStatus doodle_foreign_desc_default_bytes(struct DoodleForeignDesc *desc,
                                               const uint8_t *name,
                                               uintptr_t name_len,
                                               const uint8_t *value,
                                               uintptr_t value_len);

/**
 * Sets the descriptor's callback (E§5.2): the C function the engine runs when the foreign
 * function is called, and an opaque `user_data` passed to it verbatim. A foreign function must
 * have a callback (else `doodle_registry_add_foreign` returns `ErrContract`).
 *
 * # Safety
 * `desc` a live descriptor; `callback` a valid, non-NULL function pointer; `user_data` is
 * opaque (never dereferenced by the engine).
 */
DoodleStatus doodle_foreign_desc_set_callback(struct DoodleForeignDesc *desc,
                                              DoodleForeignFn callback,
                                              void *user_data);

/**
 * Frees a descriptor from `doodle_foreign_desc_new` that was **not** consumed by
 * `doodle_registry_add_foreign`. NULL is a no-op. Do not call this on a descriptor already
 * passed to `doodle_registry_add_foreign` (that consumed it).
 *
 * # Safety
 * `desc` must be a pointer from `doodle_foreign_desc_new` not already freed or consumed.
 */
void doodle_foreign_desc_free(struct DoodleForeignDesc *desc);

/**
 * Drives `instance` under `directive` to its next stop, writing the result to `out_outcome`
 * (E§7.3). Unbounded (runs until a capability / pause / raise / fault / completion); use
 * [`doodle_drive_slice`] to bound the run with fuel.
 *
 * # Safety
 * `instance` must be a live pointer from [`doodle_load`]; `out_outcome` must be writable.
 */
DoodleStatus doodle_drive(struct DoodleInstance *instance,
                          DoodleDirective directive,
                          struct DoodleOutcome *out_outcome);

/**
 * Like [`doodle_drive`] but runs at most `fuel` statement safe points before yielding a
 * resumable `Paused(SliceEnd)` (S-40) — the host's cooperative-yield point. Re-drive to
 * continue.
 *
 * # Safety
 * As [`doodle_drive`].
 */
DoodleStatus doodle_drive_slice(struct DoodleInstance *instance,
                                DoodleDirective directive,
                                uint64_t fuel,
                                struct DoodleOutcome *out_outcome);

/**
 * Requests cancellation (E§10.1): the drive tears down to `Faulted(Cancelled)` at its next
 * safe point. Idempotent; callable from another thread while a drive runs (the cancel flag
 * is atomic). No-op on NULL.
 *
 * # Safety
 * `instance` must be a live pointer from [`doodle_load`] (or NULL).
 */
void doodle_cancel(const struct DoodleInstance *instance);

/**
 * Writes the `index`-th bound argument handle of the parked capability request (E§7.5) to
 * `out_handle`. The handle is **host-owned** (S-17): read its value (`doodle_as_*` etc.) and
 * `doodle_release` it. `ErrContract` if the instance is not suspended on a capability;
 * `ErrIndexOutOfBounds` if `index >= DoodleOutcome::request_count`.
 *
 * # Safety
 * `instance` must be a live pointer from [`doodle_load`]; `out_handle` must be writable.
 */
DoodleStatus doodle_capability_arg(const struct DoodleInstance *instance,
                                   uint32_t index,
                                   DoodleHandle *out_handle);

/**
 * Resolves a parked capability suspension (E§7.5) with `value` as its result, then drives on
 * and writes the next stop to `out_outcome`. `value` becomes the capability call's result (a
 * `to` capability ignores it, yielding Void). `ErrContract` if the instance is not suspended
 * on a capability.
 *
 * # Safety
 * `instance` must be a live pointer from [`doodle_load`]; `out_outcome` must be writable.
 */
DoodleStatus doodle_resolve(struct DoodleInstance *instance,
                            DoodleHandle value,
                            struct DoodleOutcome *out_outcome);

/**
 * Resolves a parked capability suspension (E§7.5) by **raising** `value` at the capability
 * call site (E§9), then drives on. `ErrContract` if not suspended on a capability.
 *
 * # Safety
 * As [`doodle_resolve`].
 */
DoodleStatus doodle_resolve_raise(struct DoodleInstance *instance,
                                  DoodleHandle value,
                                  struct DoodleOutcome *out_outcome);

/**
 * Copies the described **kind** slug of the instance's most recent `Raised` outcome (E§9)
 * into `buf` (copy-out; `out_len` gets the full length). `DoodleStatus_ErrContract` if the
 * last drive did not raise.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_raised_kind(const struct DoodleInstance *instance,
                                uint8_t *buf,
                                uintptr_t cap,
                                uintptr_t *out_len);

/**
 * Copies the **message** of the instance's most recent `Raised` outcome (E§9) into `buf`
 * (copy-out). `DoodleStatus_ErrContract` if the last drive did not raise.
 *
 * # Safety
 * As [`doodle_raised_kind`].
 */
DoodleStatus doodle_raised_message(const struct DoodleInstance *instance,
                                   uint8_t *buf,
                                   uintptr_t cap,
                                   uintptr_t *out_len);

/**
 * Copies the instance's accumulated `print` output (raw UTF-8 bytes) into `buf` (copy-out;
 * `out_len` gets the full length). The output only grows; a host reads incrementally by
 * tracking how many bytes it has already consumed.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_output(const struct DoodleInstance *instance,
                           uint8_t *buf,
                           uintptr_t cap,
                           uintptr_t *out_len);

/**
 * Copies the `index`-th dotted path segment of a parked `import` request (E§6) into `buf`
 * (copy-out; `out_len` gets the full byte length). E.g. `import shapes.circle` exposes
 * `"shapes"` at index 0 and `"circle"` at index 1 (`DoodleOutcome::request_count` segments).
 * `ErrContract` if the instance is not suspended on an import; `ErrIndexOutOfBounds` past the
 * last segment.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_import_path_segment(const struct DoodleInstance *instance,
                                        uint32_t index,
                                        uint8_t *buf,
                                        uintptr_t cap,
                                        uintptr_t *out_len);

/**
 * Resolves a parked `import` (E§6) with the module's `source` (UTF-8) under the host's
 * `canonical_id` (its singleton-cache identity, L§11.3), then drives on — the module's top
 * level runs before the importer continues. `ErrContract` if not suspended on an import;
 * `ErrInvalidUtf8` if either buffer is not UTF-8.
 *
 * # Safety
 * `instance` live; `source`/`canonical_id` point to their `*_len` readable bytes;
 * `out_outcome` writable.
 */
DoodleStatus doodle_resolve_import(struct DoodleInstance *instance,
                                   const uint8_t *source,
                                   uintptr_t source_len,
                                   const uint8_t *canonical_id,
                                   uintptr_t canonical_id_len,
                                   struct DoodleOutcome *out_outcome);

/**
 * Resolves a parked `import` (E§6) as **not found**: the engine raises `module-not-found` in
 * the importer (a multi-segment path first falls back to a member import, S-7), then drives
 * on. `ErrContract` if not suspended on an import.
 *
 * # Safety
 * `instance` live; `out_outcome` writable.
 */
DoodleStatus doodle_resolve_import_not_found(struct DoodleInstance *instance,
                                             struct DoodleOutcome *out_outcome);

/**
 * Resolves a parked `import` (E§6) by **raising** `value` at the `import` site (e.g. a failed
 * fetch), then drives on. `ErrContract` if not suspended on an import.
 *
 * # Safety
 * `instance` live; `out_outcome` writable.
 */
DoodleStatus doodle_resolve_import_raise(struct DoodleInstance *instance,
                                         DoodleHandle value,
                                         struct DoodleOutcome *out_outcome);

/**
 * Loads a program from UTF-8 `source` under `config`, writing a new instance to
 * `out_instance` on success (`DoodleStatus_Ok`). The host owns the returned instance and
 * frees it with [`doodle_free`]; `config` is not consumed (free it separately).
 *
 * On a lex/parse/resolve error the status is `DoodleStatus_ErrLoad` and the human-readable
 * error text is copied into `err_buf` (up to `err_buf_cap` bytes, always NUL-free UTF-8),
 * with the full byte length written to `out_err_len` (copy-out; a too-small buffer still
 * reports the needed length). `config` may be NULL (engine defaults).
 *
 * # Safety
 * `source` must point to `source_len` readable bytes; `out_instance` must be a writable
 * `*DoodleInstance`; `err_buf` may be NULL only if `err_buf_cap` is 0; `out_err_len` and
 * `config` may be NULL. Pointers must not alias in ways C forbids.
 */
DoodleStatus doodle_load(const uint8_t *source,
                         uintptr_t source_len,
                         const struct DoodleConfig *config,
                         struct DoodleInstance **out_instance,
                         uint8_t *err_buf,
                         uintptr_t err_buf_cap,
                         uintptr_t *out_err_len);

/**
 * Like [`doodle_load`] but with host extensions from `registry` (E§5.5) — capabilities and
 * built-ins the program can call. **Consumes** `registry` (moved into the instance): the
 * pointer is invalid after this call, whether it succeeds or fails; do not free or reuse it.
 *
 * # Safety
 * As [`doodle_load`], plus `registry` must be a pointer from `doodle_registry_new` not
 * already consumed/freed.
 */
DoodleStatus doodle_load_with_registry(const uint8_t *source,
                                       uintptr_t source_len,
                                       const struct DoodleConfig *config,
                                       struct DoodleRegistry *registry,
                                       struct DoodleInstance **out_instance,
                                       uint8_t *err_buf,
                                       uintptr_t err_buf_cap,
                                       uintptr_t *out_err_len);

/**
 * Frees an instance from [`doodle_load`], running the finalizer of every live foreign value
 * (E§3.1/§4.5). NULL is a no-op. After this the pointer is invalid.
 *
 * # Safety
 * `instance` must be a pointer from `doodle_load` that has not already been freed.
 */
void doodle_free(struct DoodleInstance *instance);

/**
 * The current source position (E§8.1): the span the active frame is about to execute. `has` is
 * `false` (position zeroed) when the instance is terminal (no active frame).
 *
 * # Safety
 * `instance` live; `out_position`/`out_has` writable.
 */
DoodleStatus doodle_current_position(const struct DoodleInstance *instance,
                                     struct DoodlePosition *out_position,
                                     bool *out_has);

/**
 * The position of the subexpression just completed at a **fine** safe point (E§8.4, S-62) —
 * together with `doodle_current_result`, the "watch your expression evaluate" primitive. `has`
 * is `false` at a statement stop or when not stopped at a fine point.
 *
 * # Safety
 * `instance` live; `out_position`/`out_has` writable.
 */
DoodleStatus doodle_completed_position(const struct DoodleInstance *instance,
                                       struct DoodlePosition *out_position,
                                       bool *out_has);

/**
 * A fresh **host-owned** handle to the current result-register value (E§8.4), or
 * `DOODLE_NULL_HANDLE` when the register is empty (Void). At a fine safe point this is the
 * subexpression's value (S-62). Non-null results are host-owned — `doodle_release` them.
 *
 * # Safety
 * `instance` live; `out_handle` writable.
 */
DoodleStatus doodle_current_result(struct DoodleInstance *instance, DoodleHandle *out_handle);

/**
 * Writes the number of live stack frames (E§8.2) to `out_count` and the current **pause
 * generation** to `out_generation` — the token every per-frame accessor validates (D-M7-12).
 * Frames are addressed innermost-0. Re-read (and re-walk) after any drive/resolve.
 *
 * # Safety
 * `instance` live; `out_count`/`out_generation` writable.
 */
DoodleStatus doodle_stack_frame_count(const struct DoodleInstance *instance,
                                      uint32_t *out_count,
                                      uint32_t *out_generation);

/**
 * Fills `out_frame` with innermost-first frame `index` (E§8.2), pure data (the callable is minted
 * separately by `doodle_frame_callable`). `generation` must be the token from
 * `doodle_stack_frame_count`; a stale one → `ErrStale` (checked **before** bounds, D-M7-12), a
 * live one with `index` past the top → `ErrIndexOutOfBounds`.
 *
 * # Safety
 * `instance` live; `out_frame` writable.
 */
DoodleStatus doodle_frame_at(const struct DoodleInstance *instance,
                             uint32_t generation,
                             uint32_t index,
                             struct DoodleFrame *out_frame);

/**
 * A fresh **host-owned** handle to frame `index`'s callable (E§8.2, D-M7-13), or
 * `DOODLE_NULL_HANDLE` for a module-top / block frame (no callable — `has_callable` said so).
 * `generation` gates the `index` addressing (stale → `ErrStale`), **not** the returned handle:
 * once minted it is an ordinary host-owned handle (valid across resumes) — `doodle_release` it.
 *
 * # Safety
 * `instance` live; `out_handle` writable.
 */
DoodleStatus doodle_frame_callable(struct DoodleInstance *instance,
                                   uint32_t generation,
                                   uint32_t index,
                                   DoodleHandle *out_handle);

/**
 * Copies the host **canonical id** a position's opaque module `token` was loaded under (E§6,
 * D-M7-14) into `buf` (copy-out; `out_len` gets the full byte length) — the host resolves a
 * `DoodlePosition::module` to the source it holds. `ErrContract` if `token` names no loaded
 * module (a fabricated token; tokens come from positions/frames).
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_module_canonical_id(const struct DoodleInstance *instance,
                                        uint32_t token,
                                        uint8_t *buf,
                                        uintptr_t cap,
                                        uintptr_t *out_len);

/**
 * Writes the number of local bindings in scope in frame `index` (E§8.2). `ErrStale` on a stale
 * `generation`; `ErrIndexOutOfBounds` if `index` is past the top frame.
 *
 * # Safety
 * `instance` live; `out_count` writable.
 */
DoodleStatus doodle_frame_local_count(const struct DoodleInstance *instance,
                                      uint32_t generation,
                                      uint32_t index,
                                      uint32_t *out_count);

/**
 * Copies the name of frame `index`'s `slot`-th local (E§8.2) into `buf` (copy-out). `ErrStale`
 * on a stale `generation`; `ErrIndexOutOfBounds` if `slot` is past the frame's locals.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_frame_local_name(const struct DoodleInstance *instance,
                                     uint32_t generation,
                                     uint32_t index,
                                     uint32_t slot,
                                     uint8_t *buf,
                                     uintptr_t cap,
                                     uintptr_t *out_len);

/**
 * A fresh **host-owned** handle to frame `index`'s `slot`-th local's value (E§8.2), or
 * `DOODLE_NULL_HANDLE` if it is not yet initialized (the temporal dead zone) or the slot is
 * absent. `ErrStale` on a stale `generation`. Non-null values are host-owned — release them.
 *
 * # Safety
 * `instance` live; `out_handle` writable.
 */
DoodleStatus doodle_frame_local_value(struct DoodleInstance *instance,
                                      uint32_t generation,
                                      uint32_t index,
                                      uint32_t slot,
                                      DoodleHandle *out_handle);

/**
 * Writes the number of `with` dynamic-parameter bindings in frame `index` (E§8.2, L§5.5).
 * `ErrStale`/`ErrIndexOutOfBounds` as [`doodle_frame_local_count`].
 *
 * # Safety
 * `instance` live; `out_count` writable.
 */
DoodleStatus doodle_frame_dynamic_count(const struct DoodleInstance *instance,
                                        uint32_t generation,
                                        uint32_t index,
                                        uint32_t *out_count);

/**
 * Copies the name of frame `index`'s `slot`-th dynamic-parameter binding (E§8.2) into `buf`
 * (copy-out). `ErrStale`/`ErrIndexOutOfBounds` as [`doodle_frame_local_name`].
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_frame_dynamic_name(const struct DoodleInstance *instance,
                                       uint32_t generation,
                                       uint32_t index,
                                       uint32_t slot,
                                       uint8_t *buf,
                                       uintptr_t cap,
                                       uintptr_t *out_len);

/**
 * A fresh **host-owned** handle to frame `index`'s `slot`-th dynamic-parameter value (E§8.2),
 * or `DOODLE_NULL_HANDLE` if the cell is unbound/absent. `ErrStale` on a stale `generation`.
 *
 * # Safety
 * `instance` live; `out_handle` writable.
 */
DoodleStatus doodle_frame_dynamic_value(struct DoodleInstance *instance,
                                        uint32_t generation,
                                        uint32_t index,
                                        uint32_t slot,
                                        DoodleHandle *out_handle);

/**
 * Writes the number of module-level globals of the module named by `module_token` (E§8.2, L§5).
 * `ErrStale` on a stale `generation`. (Globals are module-scoped, but share the pause token so a
 * host re-walks after any drive — the values change with execution.)
 *
 * # Safety
 * `instance` live; `out_count` writable.
 */
DoodleStatus doodle_module_global_count(const struct DoodleInstance *instance,
                                        uint32_t generation,
                                        uint32_t module_token,
                                        uint32_t *out_count);

/**
 * Fills `out_global` with the `index`-th global of `module_token` (E§8.2): its `kind` and
 * declaration span. Its name copies out via [`doodle_module_global_name`] and its value via
 * [`doodle_module_global_value`] (same `index`). `ErrStale`/`ErrIndexOutOfBounds`.
 *
 * # Safety
 * `instance` live; `out_global` writable.
 */
DoodleStatus doodle_module_global(const struct DoodleInstance *instance,
                                  uint32_t generation,
                                  uint32_t module_token,
                                  uint32_t index,
                                  struct DoodleGlobal *out_global);

/**
 * Copies the name of `module_token`'s `index`-th global (E§8.2) into `buf` (copy-out).
 * `ErrStale`/`ErrIndexOutOfBounds`.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_module_global_name(const struct DoodleInstance *instance,
                                       uint32_t generation,
                                       uint32_t module_token,
                                       uint32_t index,
                                       uint8_t *buf,
                                       uintptr_t cap,
                                       uintptr_t *out_len);

/**
 * A fresh **host-owned** handle to the current value of `module_token`'s `index`-th global
 * (E§8.2), or `DOODLE_NULL_HANDLE` if it is not yet defined (its declaration has not executed)
 * or the index is absent. `ErrStale` on a stale `generation`. Non-null values are host-owned.
 *
 * # Safety
 * `instance` live; `out_handle` writable.
 */
DoodleStatus doodle_module_global_value(struct DoodleInstance *instance,
                                        uint32_t generation,
                                        uint32_t module_token,
                                        uint32_t index,
                                        DoodleHandle *out_handle);

/**
 * Creates an empty registry. Returns NULL only on allocation failure. Populate it in the
 * order the host wants capability ids assigned (registration order is replay identity, §11),
 * then pass it to `doodle_load_with_registry` (which consumes it) — or free an unused one
 * with `doodle_registry_free`.
 */
struct DoodleRegistry *doodle_registry_new(void);

/**
 * Frees a registry created by `doodle_registry_new` that was **not** consumed by
 * `doodle_load_with_registry`. NULL is a no-op. Do not call this on a registry already
 * passed to `doodle_load_with_registry` (that consumed it).
 *
 * # Safety
 * `registry` must be a pointer from `doodle_registry_new` not already freed or consumed.
 */
void doodle_registry_free(struct DoodleRegistry *registry);

/**
 * Registers an engine built-in by identity (E§5.5), appending it to the registry. Returns
 * `DoodleStatus_ErrContract` if the name is already registered (a host bug — each built-in
 * registers at most once). No-op returning `ErrNullPointer` on a NULL registry.
 *
 * # Safety
 * `registry` must be a live pointer from `doodle_registry_new`.
 */
DoodleStatus doodle_registry_add_builtin(struct DoodleRegistry *registry, DoodleBuiltin builtin);

/**
 * Registers a **host foreign function** from a descriptor (E§5.1/§5.2, M7.2b), appending it to
 * the registry. **Consumes** `desc` (the pointer is invalid after this call, success or
 * failure — do not free or reuse it). `ErrContract` if the descriptor has no callback set
 * (`doodle_foreign_desc_set_callback`) or its name duplicates a prior registration/reserved
 * name; `ErrNullPointer` on a NULL descriptor (nothing consumed) or a NULL registry.
 *
 * # Safety
 * `registry` a live pointer from `doodle_registry_new` (not consumed); `desc` a live pointer
 * from `doodle_foreign_desc_new` (not consumed).
 */
DoodleStatus doodle_registry_add_foreign(struct DoodleRegistry *registry,
                                         struct DoodleForeignDesc *desc);

/**
 * Makes an `Int` from an `int64_t` (E§4.3). Larger magnitudes use `doodle_make_int_decimal`.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_make_int(struct DoodleInstance *instance, int64_t value, DoodleHandle *out);

/**
 * Makes an `Int` of any magnitude from a base-10 decimal string (E§4.3). `ErrMalformedInt`
 * if the text is not a base-10 integer literal.
 *
 * # Safety
 * `instance` live; `decimal` points to `decimal_len` readable bytes; `out` writable.
 */
DoodleStatus doodle_make_int_decimal(struct DoodleInstance *instance,
                                     const uint8_t *decimal,
                                     uintptr_t decimal_len,
                                     DoodleHandle *out);

/**
 * Makes a `Float` from a `double` (E§4.3); any NaN is canonicalized (E§11).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_make_float(struct DoodleInstance *instance, double value, DoodleHandle *out);

/**
 * Makes a `Bool` (E§4.1).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_make_bool(struct DoodleInstance *instance, bool value, DoodleHandle *out);

/**
 * Makes `nil` (E§4.9).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_make_nil(struct DoodleInstance *instance, DoodleHandle *out);

/**
 * Makes a `String` from UTF-8 bytes (E§4.4); the engine validates UTF-8 and normalizes to
 * NFC. `ErrInvalidUtf8` if the bytes are not well-formed UTF-8.
 *
 * # Safety
 * `instance` live; `bytes` points to `bytes_len` readable bytes; `out` writable.
 */
DoodleStatus doodle_make_string(struct DoodleInstance *instance,
                                const uint8_t *bytes,
                                uintptr_t bytes_len,
                                DoodleHandle *out);

/**
 * Makes a **foreign value** (E§4.5): an opaque host object Doodle can hold, pass, and store
 * by identity but not inspect. `tag` is the host's type discriminator; `ptr` is an opaque
 * token returned verbatim by `doodle_foreign_ptr` and handed to `finalizer`. A non-NULL
 * `finalizer` runs **exactly once** when the value dies (E§4.5); it receives only `ptr`, so it
 * cannot re-enter the engine, and must not unwind.
 *
 * # Safety
 * `instance` live; `out` writable; `finalizer` (if non-NULL) a valid function pointer.
 */
DoodleStatus doodle_make_foreign(struct DoodleInstance *instance,
                                 uint64_t tag,
                                 uint64_t ptr,
                                 struct Option_DoodleFinalizer finalizer,
                                 DoodleHandle *out);

/**
 * Writes a foreign value's host `tag` (E§4.5). `ErrWrongKind` if the handle is not a foreign
 * value; `ErrStaleHandle` if freed.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_foreign_tag(const struct DoodleInstance *instance,
                                DoodleHandle handle,
                                uint64_t *out);

/**
 * Writes a foreign value's opaque host `ptr` (E§4.5), returned verbatim. `ErrWrongKind` if
 * the handle is not a foreign value; `ErrStaleHandle` if freed.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_foreign_ptr(const struct DoodleInstance *instance,
                                DoodleHandle handle,
                                uint64_t *out);

/**
 * Reads an `Int` as `int64_t` (E§4.3). `ErrIntOutOfRange` for a bignum (read it with
 * `doodle_as_int_decimal`); `ErrWrongKind` for a non-int; `ErrStaleHandle` if freed.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_as_int(const struct DoodleInstance *instance,
                           DoodleHandle handle,
                           int64_t *out);

/**
 * Reads a `Float` as `double` (E§4.3).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_as_float(const struct DoodleInstance *instance,
                             DoodleHandle handle,
                             double *out);

/**
 * Reads a `Bool` (E§4.1).
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_as_bool(const struct DoodleInstance *instance, DoodleHandle handle, bool *out);

/**
 * Writes whether the value is `nil` (E§4.9) — `ErrStaleHandle` if freed, never `ErrWrongKind`.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_is_nil(const struct DoodleInstance *instance, DoodleHandle handle, bool *out);

/**
 * Writes the value's kind (E§4.4). `ErrStaleHandle` if the handle is freed.
 *
 * # Safety
 * `instance` live; `out` writable.
 */
DoodleStatus doodle_kind_of(const struct DoodleInstance *instance,
                            DoodleHandle handle,
                            DoodleKind *out);

/**
 * Copies an `Int`'s value as a base-10 decimal string into `buf` (copy-out; `out_len` gets
 * the full length) — the arbitrary-precision counterpart of `doodle_as_int`.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_as_int_decimal(const struct DoodleInstance *instance,
                                   DoodleHandle handle,
                                   uint8_t *buf,
                                   uintptr_t cap,
                                   uintptr_t *out_len);

/**
 * Copies a `String`'s raw UTF-8 bytes into `buf` (copy-out; `out_len` gets the full byte
 * length). The engine keeps strings NFC, so these bytes are NFC UTF-8.
 *
 * # Safety
 * `instance` live; `buf` readable for `cap` (or NULL with `cap` 0); `out_len` may be NULL.
 */
DoodleStatus doodle_string_bytes(const struct DoodleInstance *instance,
                                 DoodleHandle handle,
                                 uint8_t *buf,
                                 uintptr_t cap,
                                 uintptr_t *out_len);

/**
 * Releases a host-owned handle (E§4.2): decrements its reference count, freeing the slot at
 * zero. `ErrStaleHandle` if already freed. A handle must be released exactly as many times
 * as it was obtained.
 *
 * # Safety
 * `instance` must be a live pointer from `doodle_load`.
 */
DoodleStatus doodle_release(struct DoodleInstance *instance, DoodleHandle handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DOODLE_H */
