#ifndef DOODLE_H
#define DOODLE_H

/* Auto-generated by cbindgen; regenerate with scripts/capi-header.sh --write. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the Doodle engine version as a NUL-terminated C string.
 *
 * The returned pointer is valid for the lifetime of the program and must not
 * be freed by the caller.
 */
const char *doodle_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DOODLE_H */
